import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function F2(props) {
  const { nodes, materials } = useGLTF(
    "/courage_ic70_2006__www.vecarz.com.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_190.geometry}
          material={materials.glass}
          position={[0, 0, 0.007]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_193.geometry}
          material={materials.glass}
          position={[0, 0, 0.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_36.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_66.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_70.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_76.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_78.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_81.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_84.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_86.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_88.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_90.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_92.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_94.geometry}
          material={materials.Cabin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_100.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_103.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_106.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_109.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_111.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_114.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_116.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_118.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_121.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_124.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_126.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_129.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_132.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_135.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_138.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_141.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_144.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_147.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_150.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_152.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_154.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_157.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_159.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_161.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_164.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_167.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_169.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_172.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_174.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_177.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_180.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_182.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_185.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_187.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_196.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_199.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_202.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_204.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_207.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_209.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_212.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_215.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_217.geometry}
          material={materials.Lights_Pod_Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_220.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_223.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_225.geometry}
          material={materials.Lights_Pod_Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_228.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_230.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_233.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_235.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_238.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_241.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_243.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_246.geometry}
          material={materials.Cabin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_249.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_251.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_254.geometry}
          material={materials.Cabin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_257.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_259.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_262.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_264.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_267.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_270.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_273.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_275.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_278.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_280.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_283.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_285.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_288.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_290.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_293.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_295.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_298.geometry}
          material={materials.Tyre_Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_300.geometry}
          material={materials.Tyre_Tread}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_303.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_305.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_307.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_310.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_313.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_315.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_318.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_321.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_323.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_326.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_328.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_330.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_332.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_334.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_336.geometry}
          material={materials.Cabin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_339.geometry}
          material={materials.Discs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_341.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_344.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_347.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_350.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_353.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_356.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_358.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_360.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_363.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_365.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_367.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_370.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_372.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_374.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_376.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_379.geometry}
          material={materials.Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_381.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_383.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_386.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_388.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_390.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_393.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_396.geometry}
          material={materials.Aerials}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_399.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_402.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_405.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_408.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_411.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_414.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_417.geometry}
          material={materials.Shiny_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_420.geometry}
          material={materials.Suspension}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_423.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_425.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_427.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_430.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_432.geometry}
          material={materials.Bare_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_434.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_437.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_440.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_443.geometry}
          material={materials.Rear_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_446.geometry}
          material={materials.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_449.geometry}
          material={materials.Car_Body_Paint}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_451.geometry}
          material={materials.Head_Lights_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_454.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_456.geometry}
          material={materials.Lights_Pod_Matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_459.geometry}
          material={materials.Head_Lights_Pod}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_461.geometry}
          material={materials.Lights_Pod_Matt}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/courage_ic70_2006__www.vecarz.com.glb");
